### ISSUE TITLE
userFeePercentage issue

### ISSUE THREAD

**Issue by jasontron21** [tronprotocol/tron-web#244] opened 2019-04-09 18:24 UTC
When we deploy our smart contract to the local network, userFeePercentage is always set to 100% even even if we set it to another value. Is this the normal behavior?  I want to use another value but I cannot.

Sullof has responded to me on discord and verified that this is a bug.

**Comment by sullof** [comment] 2019-04-09 18:34
@jasontron21 Thanks for the report. 
Are you using TronBox for the deployment or TronWeb directly or what?

**Comment by jasontron21** [comment] 2019-04-09 18:41
I actually work for Tron and am emailing on the developers behalf. They are located in Korea, so i'm just trying to take advantage of the time while they are asleep. I don't have the exact details on how they're deploying their code. Can I have the developer jump onto this ticket and have him communicate directly with you?

**Comment by sullof** [comment] 2019-04-09 18:48
Sure. Thanks

**Comment by sullof** [comment] 2019-04-09 19:19
I added some specific test (https://github.com/tronprotocol/tron-web/pull/245) and verified that TronWeb works as expected. Most likely the issue is caused by the tool used for the deployment. I am not closing it, because I would like to know the tool used to create the smart contract.

**Closed** 2019-04-11 18:25 UTC

**Comment by sullof** [comment] 2019-04-20 01:01
There was actually a problem with `userFeePercentage` set to zero. Fixed in https://github.com/tronprotocol/tron-web/pull/262
